

name: Java CI with Maven

on:
  schedule:
    - cron: "0 9 * * 1-5" # Runs at 9:00 AM UTC, Monday to Friday
  workflow_dispatch: # Allows manual trigger

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

